### ISSUE TITLE
Setting thermostat temperature fails: Exception in async_timer_finished when dispatching 'scheduler_timer_finished'

### ISSUE THREAD

**Issue by battlebyte** [nielsfaber/scheduler-component#214]
### Checklist
- [ x] I checked for similar existing issues (both open and closed) before posting.
- [ x] I am running the latest version.

### Expected behavior
I expect the thermostat temperature to be set at the right value when the day/time condition is met.

### Actual behavior
The day/time condition triggers the action but setting the value fails with the following exception:

Logger: homeassistant.util.logging
Source: util/logging.py:156 
First occurred: 1 October 2022, 21:11:07 (21 occurrences) 
Last logged: 10:20:00

Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('d0fa99',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 258, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 259, in async_queue_actions await queue.async_start() File "/config/custom_components/scheduler/actions.py", line 381, in async_start await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 514, in async_process_queue skip_action = not action_has_effect(action, self.hass) File "/config/custom_components/scheduler/actions.py", line 217, in action_has_effect return float(state.attributes.get(ATTR_TARGET_TEMP_LOW)) != float( TypeError: float() argument must be a string or a real number, not 'NoneType'
Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('82b9a9',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 258, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 259, in async_queue_actions await queue.async_start() File "/config/custom_components/scheduler/actions.py", line 381, in async_start await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 514, in async_process_queue skip_action = not action_has_effect(action, self.hass) File "/config/custom_components/scheduler/actions.py", line 217, in action_has_effect return float(state.attributes.get(ATTR_TARGET_TEMP_LOW)) != float( TypeError: float() argument must be a string or a real number, not 'NoneType'
Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('842207',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 258, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 259, in async_queue_actions await queue.async_start() File "/config/custom_components/scheduler/actions.py", line 381, in async_start await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 514, in async_process_queue skip_action = not action_has_effect(action, self.hass) File "/config/custom_components/scheduler/actions.py", line 217, in action_has_effect return float(state.attributes.get(ATTR_TARGET_TEMP_LOW)) != float( TypeError: float() argument must be a string or a real number, not 'NoneType'
Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('13e1d4',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 258, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 259, in async_queue_actions await queue.async_start() File "/config/custom_components/scheduler/actions.py", line 381, in async_start await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 514, in async_process_queue skip_action = not action_has_effect(action, self.hass) File "/config/custom_components/scheduler/actions.py", line 217, in action_has_effect return float(state.attributes.get(ATTR_TARGET_TEMP_LOW)) != float( TypeError: float() argument must be a string or a real number, not 'NoneType'
Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('82b9a9',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 232, in async_timer_updated await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 259, in async_queue_actions await queue.async_start() File "/config/custom_components/scheduler/actions.py", line 381, in async_start await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 514, in async_process_queue skip_action = not action_has_effect(action, self.hass) File "/config/custom_components/scheduler/actions.py", line 217, in action_has_effect return float(state.attributes.get(ATTR_TARGET_TEMP_LOW)) != float( TypeError: float() argument must be a string or a real number, not 'NoneType'

### Steps to Reproduce

This is an example configuration for the scheduler that fails:
![image](https://user-images.githubusercontent.com/1140998/193445684-4c9b6c2d-b4d2-4852-86e4-9ac44cd98984.png)

I have setup configurations to control the blinds which work correctly. It only fails with my thermostat components.

**Comment by tane64** [comment]
all my old setpoints are working fine.
can't change or set a new  setpoint.

**Comment by jonas5** [comment]
I have the exact same problems. 
The scheduler does not turn off the device when 'off' period is set with termostat opted as conditional.

I have to manually turn device with termostats off.

Please attend, running latest home assistant 2022.10.2

**Comment by battlebyte** [comment]
There is no "target_temp_low" in this component. The properties of the climate entity are:

hvac_modes:
  - 'off'
  - heat_cool
min_temp: 0.5
max_temp: 70
target_temp_step: 0.1
current_temperature: 21
temperature: 21
friendly_name: 'Dormitorio '
supported_features: 1

**Comment by nielsfaber** [comment]
@battlebyte There's your problem.
The `heat_cool` mode works with an upper and lower bound for temperature.
These need to be provided in the `target_temperature_low` and `target_temperature_high` properties of the climate entity.
Also the `supported_features` of this device is wrong.  It should be 2 in case the device supports the `heat_cool` mode, 1 is for a device supporting only `heat` (or `cool`).
This can be found here as well: https://developers.home-assistant.io/docs/core/entity/climate/

I suggest to report this bug in HA (or zigbee2mqtt if applicable). I cannot solve this.

**Comment by nielsfaber** [comment]
I made a release v3.2.11 which should solve this issue.
Note that the problem is actually caused by your climate device, I would recommend to notify the developer of the integration for the device of this issue.

Scheduler will normally check whether the action has an effect (i.e. before changing climate setpoint, check the current setpoint).
This check will now be skipped in case your climate device doesn't have the `target_temperature` (or `target_temperature_low` and `target_temperature_high` in case of temperature regulation with a min+max value) properties.
This could result in extra/unnecessary communication with your climate device.

**Comment by mj1985** [comment]
I upgraded to 3.2.11 and still get the same error (I think), the scheduler is not working anymore with my Eurotronic Spirit Zigbee via ZHA. I will get some Nedis/Siterwell thermostats soon, according to the zha quirks, this should fix the problem

Error:
```
2022-11-14 07:00:10.004 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/actions.py", line 494, in async_timer_finished
await self.async_process_queue(task_idx + 1)
File "/config/custom_components/scheduler/actions.py", line 519, in async_process_queue
skip_action = not action_has_effect(action, self.hass)
File "/config/custom_components/scheduler/actions.py", line 210, in action_has_effect
return float(state.attributes.get(ATTR_TEMPERATURE, 0)) != float(
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by nielsfaber** [comment]
@mj1985 I saw that my previous fix was not working in some cases. I made release v3.2.12 which should fix your case as well. Please try it out.

**Comment by mj1985** [comment]
Thank you @nielsfaber The scheduler is working again, without any error (Nedis thermostat and Eurotronic, too)
