### ISSUE TITLE
Unable to save new changes

### ISSUE THREAD

**Issue by MS-Turbo** [nielsfaber/scheduler-component#227]
Running latest version of everything

When trying to change any setting, the scheduler "jumps back" to old settings.
This issue happens to all type of schedules, temperatur changes, time changes, name changes and so on.

Any thoughts on why this is happening? 

<img width="800" alt="Skjermbilde 2022-11-27 kl  19 02 27" src="https://user-images.githubusercontent.com/65830570/204152133-c0f59c83-847a-4f75-a2bc-e59ef3039cf2.png">

**Comment by nielsfaber** [comment]
This is a problem of 2 versions before, it’s fixed in the latest release.
You should clear your browser cache or something.

**Comment by MS-Turbo** [comment]
> This is a problem of 2 versions before, it’s fixed in the latest release. You should clear your browser cache or something.

Still not working here.  

1. Deleted all cache (tried the samne both in crome and brawe) 
2. Reinstalled HACS scheduler addon v3.2.12
3. Restarted Home Assistent

When trying to change temperature in a schedule, it just jumps back before beeing able to save changes

Any other soulutions I can try?

**Comment by nielsfaber** [comment]
Please check your browser console logs (under developer tools or similar).
There should be a badge displayed there with the version of the card which is running.

I’m still convinced this is a problem due to old version. If you can prove otherwise, I’m willing to dive into it.

**Comment by MS-Turbo** [comment]
Hi. Not sure what to look for but here is a screenshot. 
One interesting find...this issue is only occurring when accessing HA through nabucasa. When connected by local ip, everything works fine.  Så maybe the fix is not solved other then local?

<img width="1262" alt="Skjermbilde 2022-11-30 kl  23 58 57" src="https://user-images.githubusercontent.com/65830570/204926868-c96dc7ab-dd88-4f5a-b7ca-a8d07bda4ae2.png">

**Comment by nielsfaber** [comment]
> Not sure what to look for

This:
![image](https://user-images.githubusercontent.com/16861605/204973440-7a8af578-0e5b-4c84-9382-0f3e042cac7f.png)


In the release notes for v2.3.7 of the card you can read:
> Fixed a bug introduced in HA 2022.9 causing settings in the card to be reverted every few seconds while making changes.

You need to erase your browser cache to solve the issue. It is still holding an older version of the code of the card.

**Comment by omarantelmi** [comment]
The problem seems to persist for me too, even when accessing from a device that has never been used

**Comment by nielsfaber** [comment]
@omarantelmi update to v2.3.7 or newer to solve the problem.
If the problem persists after the update, follow https://github.com/nielsfaber/scheduler-component/issues/227#issuecomment-1329000471
If the browser logs show v2.3.6 or beforel, while you installed v.2.3.7 or newer -> browser cache issue.

**Comment by MS-Turbo** [comment]
Update on my rookie mistake on this issue.
Deleting cache did not work and I also tried different browsers, but the problem was an old version of the scheduler card in HACS that needed update. My mistake was looking NOT at the scheduler card, but at the scheduler component in HACS witch has the similar software version series. 


<img width="862" alt="Skjermbilde 2022-12-02 kl  16 10 25" src="https://user-images.githubusercontent.com/65830570/205324180-b146a044-5c0c-4624-98d2-191ba6290753.png">
<img width="877" alt="Skjermbilde 2022-12-02 kl  16 10 35" src="https://user-images.githubusercontent.com/65830570/205324204-e22e72a7-6454-4f9d-83db-bd874558b880.png">

**Comment by catalinbordan** [comment]
Here I had the same issues; did not revaluate the conditions on update of states and the issues described here. I was thinking something broke the updates of new versions of homeassistant and then said to check if other have same issues here open on github. Investigating, I have found that my scheduler card was almost having same version format like scheduler integration 3.1.xx witch is > 2.4.1, so HACS did not let me know that I have new update and off course problems because different version.
I redownloaded and now I have version 2.4.1 listed on HACS + make a small modification on my schedulers to fix it.
I suppose something gone wrong with versioning on scheduler card on HACS and a lot o people don't know because HACS did not trigger anymore an notification of a new update because of bad version number.
Thanks!

**Comment by nielsfaber** [comment]
@catalinbordan All releases of scheduler-card can be found in the [releases page](https://github.com/nielsfaber/scheduler-card/releases).
There is no 3.x.x yet, latest is 2.4.1.
It would be helpful if someone experiencing this problem could (before redownloading) check the [actual version](https://github.com/nielsfaber/scheduler-card#checking-card-version) which is running.
I have no idea what is causing this issue. I'm not sure if the problem is on the side of scheduler or HACS either.
