### ISSUE TITLE
Scheduler announced future problem

### ISSUE THREAD

**Issue by maherran** [nielsfaber/scheduler-component#377]
### Checklist
- [ ] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[Schedulet for thermostat]

### Actual behavior
[IMO it's working correctly]

### Steps to Reproduce
[Explain how to see the behaviour]

I don't know how to report, but I'm having a message under register telling:

Detected that custom integration 'scheduler' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/scheduler/switch.py, line 97: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues.
If I'm not wrong, the problem is related to class MigratableStore(Store).

Please, ask me for additional information in case you need it.

**Comment by xconverge** [comment]
This is fixed on the main branch already https://github.com/nielsfaber/scheduler-component/pull/375

**Comment by maherran** [comment]
But the message is still appearing on HA...
Shouldn't it disappear?

**Comment by xconverge** [comment]
> But the message is still appearing on HA... Shouldn't it disappear?

There has not been a release with this commit yet

**Comment by xconverge** [comment]
this is released now

**Comment by nielsfaber** [comment]
Yes indeed, please update to the latest version. We can close this.
